Repository mhenrixon/sidekiq-unique-jobs, pull requests merged in 2018-06, with the labels that each got.

#265 Add explicit concurrent-ruby dependency.
  .codeclimate.yml
  .rubocop.yml
  sidekiq-unique-jobs.gemspec
Labels: enhancement

#267 Use ruby 2.5.1
  .travis.yml
  Gemfile
  gemfiles/sidekiq_4.0.gemfile
  gemfiles/sidekiq_4.1.gemfile
  gemfiles/sidekiq_4.2.gemfile
  gemfiles/sidekiq_5.0.gemfile
  gemfiles/sidekiq_develop.gemfile
  rails_example/Gemfile
  rails_example/Rakefile
  rails_example/bin/bundle
  rails_example/bin/check_or_setup_db
  rails_example/bin/setup
  rails_example/bin/update
  rails_example/common-services.yml
  spec/spec_helper.rb
  spec/unit/cli_spec.rb
Labels: enhancement

#252 Allow `jobs keys` to default to listing all keys
  lib/sidekiq_unique_jobs/cli.rb
Labels: bug

#268 Minor adjustments
  .gitignore
  .rubocop.yml
  .travis.yml
  lib/sidekiq_unique_jobs/lock.rb
  lib/sidekiq_unique_jobs/unique_args.rb
  rails_example/Gemfile
  rails_example/config/initializers/new_framework_defaults.rb
  rails_example/db/schema.rb
  rails_example/spec/controllers/work_controller_mock_spec.rb
  rails_example/spec/factories/posts.rb
  spec/jobs/main_job.rb
  spec/jobs/notify_worker.rb
  spec/jobs/until_global_timeout_job.rb
  spec/spec_helper.rb
  spec/unit/cli_spec.rb
Labels: enhancement

#269 Improve documentation
  README.md
Labels: documentation

#273 Reject while scheduling
  Gemfile
  README.md
  examples/while_executing_reject_job.rb
  gemfiles/sidekiq_4.0.gemfile
  gemfiles/sidekiq_4.1.gemfile
  gemfiles/sidekiq_4.2.gemfile
  gemfiles/sidekiq_5.0.gemfile
  gemfiles/sidekiq_5.1.gemfile
  gemfiles/sidekiq_develop.gemfile
  lib/sidekiq/simulator.rb
  lib/sidekiq_unique_jobs/client/middleware.rb
  lib/sidekiq_unique_jobs/constants.rb
  lib/sidekiq_unique_jobs/lock/while_executing.rb
  lib/sidekiq_unique_jobs/lock/while_executing_reject.rb
  lib/sidekiq_unique_jobs/lock/while_executing_requeue.rb
  lib/sidekiq_unique_jobs/locksmith.rb
  lib/sidekiq_unique_jobs/options_with_fallback.rb
  lib/sidekiq_unique_jobs/server/middleware.rb
  lib/sidekiq_unique_jobs/timeout.rb
  lib/sidekiq_unique_jobs/util.rb
  redis/create.lua
  redis/delete.lua
  redis/signal.lua
  spec/integration/sidekiq_unique_jobs/client/middleware_spec.rb
  spec/integration/sidekiq_unique_jobs/lock/while_executing_reject_spec.rb
  spec/integration/sidekiq_unique_jobs/locksmith_spec.rb
  spec/spec_helper.rb
  spec/support/matchers/redis_matchers.rb
  spec/support/ruby_meta.rb
  spec/support/sidekiq_helpers.rb
  spec/support/sidekiq_meta.rb
  spec/support/version_check.rb
  spec/unit/sidekiq_unique_jobs/lock/while_executing_reject_spec.rb
Labels: enhancement, master

#275 Code smells
  .reek
  examples/long_running_run_lock_expiration_job.rb
  lib/sidekiq/simulator.rb
  lib/sidekiq_unique_jobs.rb
  lib/sidekiq_unique_jobs/cli.rb
  lib/sidekiq_unique_jobs/client/middleware.rb
  lib/sidekiq_unique_jobs/connection.rb
  lib/sidekiq_unique_jobs/constants.rb
  lib/sidekiq_unique_jobs/exceptions.rb
  lib/sidekiq_unique_jobs/lock/base_lock.rb
  lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb
  lib/sidekiq_unique_jobs/lock/until_executed.rb
  lib/sidekiq_unique_jobs/lock/while_executing.rb
  lib/sidekiq_unique_jobs/lock/while_executing_reject.rb
  lib/sidekiq_unique_jobs/lock/while_executing_requeue.rb
  lib/sidekiq_unique_jobs/locksmith.rb
  lib/sidekiq_unique_jobs/logging.rb
  lib/sidekiq_unique_jobs/options_with_fallback.rb
  lib/sidekiq_unique_jobs/scripts.rb
  lib/sidekiq_unique_jobs/server/middleware.rb
  lib/sidekiq_unique_jobs/sidekiq_unique_ext.rb
  lib/sidekiq_unique_jobs/sidekiq_worker_methods.rb
  lib/sidekiq_unique_jobs/testing.rb
  lib/sidekiq_unique_jobs/timeout/calculator.rb
  lib/sidekiq_unique_jobs/unique_args.rb
  lib/sidekiq_unique_jobs/unlockable.rb
  lib/sidekiq_unique_jobs/util.rb
  spec/examples/expiring_job_spec.rb
  spec/examples/long_running_run_lock_expiration_job_spec.rb
  spec/integration/sidekiq_unique_jobs/client/middleware_spec.rb
  spec/integration/sidekiq_unique_jobs/lock/until_and_while_executing_spec.rb
  spec/integration/sidekiq_unique_jobs/locksmith_spec.rb
  spec/integration/sidekiq_unique_jobs/server/middleware_spec.rb
  spec/support/matchers/redis_matchers.rb
  spec/support/sidekiq_helpers.rb
  spec/support/unique_macros.rb
  spec/support/version_check.rb
  spec/unit/sidekiq_unique_jobs/cli_spec.rb
  spec/unit/sidekiq_unique_jobs/client/middleware_spec.rb
  spec/unit/sidekiq_unique_jobs/lock/base_lock_spec.rb
  spec/unit/sidekiq_unique_jobs/lock/until_executed_spec.rb
  spec/unit/sidekiq_unique_jobs/lock/while_executing_reject_spec.rb
  spec/unit/sidekiq_unique_jobs/options_with_fallback_spec.rb
  spec/unit/sidekiq_unique_jobs/scripts_spec.rb
  spec/unit/sidekiq_unique_jobs/server/middleware_spec.rb
  spec/unit/sidekiq_unique_jobs/sidekiq_unique_ext_spec.rb
  spec/unit/sidekiq_unique_jobs/sidekiq_worker_methods_spec.rb
  spec/unit/sidekiq_unique_jobs/timeout/calculator_spec.rb
  spec/unit/sidekiq_unique_jobs/unique_args_spec.rb
  spec/unit/sidekiq_unique_jobs/unlockable_spec.rb
  spec/unit/sidekiq_unique_jobs/util_spec.rb
  spec/unit/sidekiq_unique_jobs_spec.rb
Labels: enhancement, master

#279 Adds guard-reek
  Gemfile
  Guardfile
  gemfiles/sidekiq_4.0.gemfile
  gemfiles/sidekiq_4.1.gemfile
  gemfiles/sidekiq_4.2.gemfile
  gemfiles/sidekiq_5.0.gemfile
  gemfiles/sidekiq_5.1.gemfile
  gemfiles/sidekiq_develop.gemfile
Labels: enhancement, master

#281 Adds legacy support
  lib/sidekiq_unique_jobs/locksmith.rb
  lib/sidekiq_unique_jobs/options_with_fallback.rb
  redis/acquire_lock.lua
  redis/create.lua
  redis/delete.lua
  redis/signal.lua
  spec/integration/sidekiq_unique_jobs/legacy_lock_spec.rb
  spec/integration/sidekiq_unique_jobs/locksmith_spec.rb
Labels: enhancement, master

#283 Remove some misleading information
  README.md
Labels: documentation

#282 Drop jobs hash
  CHANGELOG.md
  redis/delete.lua
  redis/release_lock.lua
  spec/integration/sidekiq_unique_jobs/legacy_lock_spec.rb
  spec/support/sidekiq_helpers.rb
Labels: bug, master

#284 Fix waiting for locks
  .dockerignore
  .reek
  examples/until_and_while_executing_job.rb
  lib/sidekiq/simulator.rb
  lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb
  lib/sidekiq_unique_jobs/lock/until_executed.rb
  lib/sidekiq_unique_jobs/lock/until_executing.rb
  lib/sidekiq_unique_jobs/lock/while_executing.rb
  lib/sidekiq_unique_jobs/lock/while_executing_reject.rb
  lib/sidekiq_unique_jobs/locksmith.rb
  lib/sidekiq_unique_jobs/sidekiq_unique_ext.rb
  lib/sidekiq_unique_jobs/timeout.rb
  rails_example/.env.test
  rails_example/Gemfile
  rails_example/Procfile
  rails_example/README.rdoc
  rails_example/app/controllers/work_controller.rb
  rails_example/app/workers/while_executing_worker.rb
  rails_example/bin/setup
  rails_example/bin/update
  rails_example/common-services.yml
  rails_example/config/cable.yml
  rails_example/config/database.docker.yml
  rails_example/config/environments/development.rb
  rails_example/config/environments/test.rb
  rails_example/config/puma.rb
  rails_example/config/sidekiq.yml
  rails_example/docker-compose.yml
  rails_example/spec/controllers/work_controller_spec.rb
  rails_example/spec/rails_helper.rb
  rails_example/spec/spec_helper.rb
  redis/create.lua
  spec/integration/sidekiq_unique_jobs/client/middleware_spec.rb
  spec/integration/sidekiq_unique_jobs/lock/until_and_while_executing_spec.rb
  spec/integration/sidekiq_unique_jobs/lock/until_executed_spec.rb
  spec/integration/sidekiq_unique_jobs/locksmith_spec.rb
  spec/integration/sidekiq_unique_jobs/server/middleware/until_and_while_executing_spec.rb
  spec/integration/sidekiq_unique_jobs/server/middleware_spec.rb
  spec/spec_helper.rb
  spec/support/shared_examples/an_executing_lock_with_error_handling.rb
  spec/support/sidekiq_helpers.rb
  spec/unit/sidekiq_unique_jobs/lock/until_and_while_executing_spec.rb
  spec/unit/sidekiq_unique_jobs/lock/until_executing_spec.rb
  spec/unit/sidekiq_unique_jobs/lock/while_executing_reject_spec.rb
  spec/unit/sidekiq_unique_jobs/lock/while_executing_spec.rb
  spec/unit/sidekiq_unique_jobs/sidekiq_unique_ext_spec.rb
Labels: bug, master

#285 Only unlock not delete
  lib/sidekiq_unique_jobs/lock/base_lock.rb
  lib/sidekiq_unique_jobs/unique_args.rb
  spec/examples/my_unique_job_spec.rb
  spec/integration/sidekiq_unique_jobs/client/middleware_spec.rb
  spec/integration/sidekiq_unique_jobs/server/middleware/until_and_while_executing_spec.rb
  spec/support/sidekiq_helpers.rb
Labels: enhancement, master

#286 Prepare for v6
  .github/ISSUE_TEMPLATE/bug_report.md
  .gitignore
  README.md
  lib/sidekiq_unique_jobs/constants.rb
  lib/sidekiq_unique_jobs/lock/base_lock.rb
  lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb
  lib/sidekiq_unique_jobs/lock/until_executed.rb
  lib/sidekiq_unique_jobs/lock/until_executing.rb
  lib/sidekiq_unique_jobs/lock/until_expired.rb
  lib/sidekiq_unique_jobs/lock/while_executing.rb
  lib/sidekiq_unique_jobs/lock/while_executing_reject.rb
  lib/sidekiq_unique_jobs/lock/while_executing_requeue.rb
  lib/sidekiq_unique_jobs/options_with_fallback.rb
  lib/sidekiq_unique_jobs/server/middleware.rb
  lib/sidekiq_unique_jobs/sidekiq_worker_methods.rb
  lib/sidekiq_unique_jobs/unique_args.rb
  spec/integration/sidekiq_unique_jobs/lock/until_and_while_executing_spec.rb
  spec/integration/sidekiq_unique_jobs/lock/until_executed_spec.rb
  spec/integration/sidekiq_unique_jobs/lock/until_expired_spec.rb
  spec/integration/sidekiq_unique_jobs/lock/while_executing_reject_spec.rb
  spec/integration/sidekiq_unique_jobs/lock/while_executing_spec.rb
  spec/support/shared_examples/an_executing_lock_with_error_handling.rb
  spec/support/shared_examples/with_a_stubbed_locksmith.rb
  spec/unit/sidekiq_unique_jobs/lock/base_lock_spec.rb
  spec/unit/sidekiq_unique_jobs/lock/until_and_while_executing_spec.rb
  spec/unit/sidekiq_unique_jobs/lock/until_executed_spec.rb
  spec/unit/sidekiq_unique_jobs/lock/until_executing_spec.rb
  spec/unit/sidekiq_unique_jobs/lock/until_expired_spec.rb
  spec/unit/sidekiq_unique_jobs/lock/while_executing_reject_spec.rb
  spec/unit/sidekiq_unique_jobs/lock/while_executing_spec.rb
  spec/unit/sidekiq_unique_jobs/server/middleware_spec.rb
Labels: enhancement, master

#287 Rename command line binary
  .reek
  .reek.yml
  .travis.yml
  README.md
  bin/uniquejobs
  sidekiq-unique-jobs.gemspec
Labels: bug, master
