Repository mhenrixon/sidekiq-unique-jobs, pull requests merged in 2019-10, with the labels that each got.

#425 Bump ruby versions in Travis CI
  .travis.yml
Labels: enhancement

#426 Fix sidekiq develop
  .travis.yml
  Gemfile
  lib/sidekiq_unique_jobs/version_check.rb
  spec/sidekiq_unique_jobs/key_spec.rb
Labels: bug, master, v7.x

#420 Copy working setup from master
  .codeclimate.yml
  .rubocop.yml
  .simplecov
  .travis.yml
  .yardopts
  Appraisals
  Gemfile
  Guardfile
  gemfiles/sidekiq_4.0.gemfile
  gemfiles/sidekiq_4.1.gemfile
  gemfiles/sidekiq_4.2.gemfile
  gemfiles/sidekiq_5.0.gemfile
  gemfiles/sidekiq_5.1.gemfile
  gemfiles/sidekiq_5.2.gemfile
  gemfiles/sidekiq_6.0.gemfile
  gemfiles/sidekiq_develop.gemfile
  lib/sidekiq_unique_jobs.rb
  lib/sidekiq_unique_jobs/cli.rb
  lib/sidekiq_unique_jobs/constants.rb
  lib/sidekiq_unique_jobs/locksmith.rb
  lib/sidekiq_unique_jobs/middleware.rb
  lib/sidekiq_unique_jobs/sidekiq_unique_jobs.rb
  lib/sidekiq_unique_jobs/version_check.rb
  lib/sidekiq_unique_jobs/web.rb
  lib/sidekiq_unique_jobs/web/helpers.rb
  sidekiq-unique-jobs.gemspec
  spec/integration/sidekiq/retry_set_spec.rb
  spec/integration/sidekiq_unique_jobs/client/middleware_spec.rb
  spec/integration/sidekiq_unique_jobs/server/middleware_spec.rb
  spec/support/retry.rb
  spec/support/ruby_meta.rb
  spec/support/sidekiq_meta.rb
  spec/support/version_check.rb
  spec/unit/sidekiq_unique_jobs/cli_spec.rb
  spec/unit/sidekiq_unique_jobs/lock/base_lock_spec.rb
  spec/unit/sidekiq_unique_jobs/options_with_fallback_spec.rb
  spec/unit/sidekiq_unique_jobs/scripts_spec.rb
  spec/unit/sidekiq_unique_jobs/sidekiq/api_spec.rb
  spec/unit/sidekiq_unique_jobs/sidekiq_worker_methods_spec.rb
  spec/unit/sidekiq_unique_jobs/unique_args_spec.rb
  spec/unit/sidekiq_unique_jobs/util_spec.rb
  spec/unit/sidekiq_unique_jobs/version_check_spec.rb
  spec/unit/sidekiq_unique_jobs_spec.rb
Labels: enhancement, v6.x

#430 Include redis directory
  .travis.yml
  Rakefile
  sidekiq-unique-jobs.gemspec
Labels: bug, v6.x

#429 Allow Sidekiq::Context to be used for logging
  .reek.yml
  .rubocop.yml
  .travis.yml
  Gemfile
  Rakefile
  gemfiles/sidekiq_4.0.gemfile
  gemfiles/sidekiq_4.1.gemfile
  gemfiles/sidekiq_4.2.gemfile
  gemfiles/sidekiq_5.0.gemfile
  gemfiles/sidekiq_5.1.gemfile
  gemfiles/sidekiq_5.2.gemfile
  gemfiles/sidekiq_6.0.gemfile
  gemfiles/sidekiq_develop.gemfile
  lib/sidekiq_unique_jobs/cli.rb
  lib/sidekiq_unique_jobs/logging.rb
  lib/sidekiq_unique_jobs/logging/middleware_context.rb
  lib/sidekiq_unique_jobs/orphans/manager.rb
  lib/sidekiq_unique_jobs/upgrade_locks.rb
  spec/sidekiq_unique_jobs/logging_spec.rb
  spec/spec_helper.rb
  spec/support/sidekiq/logging.rb
Labels: bug, master, v7.x

#431 Pass redis_version into scripts
  .rubocop.yml
  lib/sidekiq_unique_jobs/batch_delete.rb
  lib/sidekiq_unique_jobs/config.rb
  lib/sidekiq_unique_jobs/locksmith.rb
  lib/sidekiq_unique_jobs/lua/delete.lua
  lib/sidekiq_unique_jobs/lua/delete_by_digest.lua
  lib/sidekiq_unique_jobs/lua/lock.lua
  lib/sidekiq_unique_jobs/lua/reap_orphans.lua
  lib/sidekiq_unique_jobs/lua/shared/_common.lua
  lib/sidekiq_unique_jobs/lua/unlock.lua
  lib/sidekiq_unique_jobs/lua/upgrade.lua
  lib/sidekiq_unique_jobs/script/caller.rb
  lib/sidekiq_unique_jobs/sidekiq_unique_jobs.rb
  lib/sidekiq_unique_jobs/upgrade_locks.rb
  spec/sidekiq_unique_jobs/sidekiq_unique_jobs_spec.rb
Labels: bug, master, v7.x

#433 Drop support for almost EOL ruby 2.4
  .rubocop.yml
  .travis.yml
  sidekiq-unique-jobs.gemspec
  spec/sidekiq_unique_jobs/cli_spec.rb
Labels: enhancement, master, v7.x

#434 Brpoplpush redis script
  .reek.yml
  .rubocop.yml
  .travis.yml
  lib/sidekiq_unique_jobs.rb
  lib/sidekiq_unique_jobs/exceptions.rb
  lib/sidekiq_unique_jobs/lock/until_expired.rb
  lib/sidekiq_unique_jobs/orphans/manager.rb
  lib/sidekiq_unique_jobs/script.rb
  lib/sidekiq_unique_jobs/script/caller.rb
  lib/sidekiq_unique_jobs/script/template.rb
  sidekiq-unique-jobs.gemspec
  spec/sidekiq_unique_jobs/orphans/manager_spec.rb
  spec/sidekiq_unique_jobs/script/caller_spec.rb
  spec/sidekiq_unique_jobs/script_spec.rb
Labels: enhancement, master, v7.x
