Repository mhenrixon/sidekiq-unique-jobs, pull requests merged in 2020-06, with the labels that each got.

#512 Move dev-gems from gemspec to gemfile
  Gemfile
Labels: enhancement, v7.x

#513 Move gems to gemfile
  .github/workflows/rspec.yml
  .travis.yml
Labels: enhancement, v7.x

#516 Prevent indefinitely looping entries
  .github/workflows/lint.yml
  .github/workflows/rspec.yml
  .reek.yml
  bin/appraisal
  gemfiles/sidekiq_4.0.gemfile
  gemfiles/sidekiq_4.1.gemfile
  gemfiles/sidekiq_4.2.gemfile
  gemfiles/sidekiq_5.0.gemfile
  gemfiles/sidekiq_5.1.gemfile
  gemfiles/sidekiq_5.2.gemfile
  gemfiles/sidekiq_6.0.gemfile
  gemfiles/sidekiq_develop.gemfile
  lib/sidekiq_unique_jobs/changelog.rb
  lib/sidekiq_unique_jobs/digests.rb
  lib/sidekiq_unique_jobs/orphans/ruby_reaper.rb
  lib/sidekiq_unique_jobs/redis/entity.rb
  lib/sidekiq_unique_jobs/upgrade_locks.rb
  spec/sidekiq_unique_jobs/locksmith_spec.rb
  spec/spec_helper.rb
  spec/support/sidekiq_unique_jobs/testing.rb
Labels: bug, v7.x

#518 Prevent reaping of active jobs
  .reek.yml
  lib/sidekiq_unique_jobs/lua/reap_orphans.lua
  lib/sidekiq_unique_jobs/lua/shared/_find_digest_in_process_set.lua
  lib/sidekiq_unique_jobs/on_conflict/reject.rb
  lib/sidekiq_unique_jobs/orphans/ruby_reaper.rb
  spec/sidekiq/retry_set_spec.rb
  spec/sidekiq_unique_jobs/lua/delete_job_by_digest_spec.rb
  spec/sidekiq_unique_jobs/lua/reap_orphans_spec.rb
  spec/sidekiq_unique_jobs/on_conflict/replace_spec.rb
  spec/sidekiq_unique_jobs/orphans/reaper_spec.rb
Labels: bug, v7.x

#520 Backport #465 to 6.x series
  sidekiq-unique-jobs.gemspec
Labels: bug, v6.x

#521 Exit early when no results are returned from LRANGE given jobs might already processed
  lib/sidekiq_unique_jobs/lua/shared/_delete_from_queue.lua
Labels: bug, master, v7.x
