Repository mhenrixon/sidekiq-unique-jobs, pull requests merged in 2020-05, with the labels that each got.

#503 Fix access to both server and client conflict
  lib/sidekiq_unique_jobs/core_ext.rb
  lib/sidekiq_unique_jobs/lock_config.rb
Labels: bug, master, v7.x

#504 Deprecate configuration options with `default_`
  lib/sidekiq_unique_jobs/config.rb
  lib/sidekiq_unique_jobs/lock_timeout.rb
  lib/sidekiq_unique_jobs/lock_ttl.rb
  lib/sidekiq_unique_jobs/sidekiq_unique_jobs.rb
  sidekiq-unique-jobs.gemspec
  spec/sidekiq_unique_jobs/config_spec.rb
  spec/sidekiq_unique_jobs/lock_timeout_spec.rb
  spec/sidekiq_unique_jobs/sidekiq_unique_jobs_spec.rb
Labels: bug, documentation, master, v7.x

#505 Try GitHub actions
  .github/workflows/lint.yml
  .github/workflows/rspec.yml
  lib/sidekiq_unique_jobs/config.rb
  lib/sidekiq_unique_jobs/core_ext.rb
Labels: enhancement, master, v5.x, v6.x, v7.x

#506 Deep stringify worker options to account for hash in on_conflict
  lib/sidekiq_unique_jobs/sidekiq_worker_methods.rb
  spec/sidekiq_unique_jobs/sidekiq_worker_methods_spec.rb
  spec/support/workers/unique_job_on_conflict_hash.rb
Labels: bug, master, v7.x

#508 Expire reaper when not checking in
  lib/sidekiq_unique_jobs/orphans/manager.rb
  spec/sidekiq_unique_jobs/orphans/manager_spec.rb
  spec/sidekiq_unique_jobs/web/helpers_spec.rb
Labels: bug, master, v7.x
