Repository mhenrixon/sidekiq-unique-jobs, pull requests merged in 2020-03, with the labels that each got.

#465 Update gemspec: thor
  sidekiq-unique-jobs.gemspec
Labels: enhancement

#474 Split calculator into two separate
  .reek.yml
  .rubocop.yml
  Gemfile
  gemfiles/sidekiq_4.0.gemfile
  gemfiles/sidekiq_4.1.gemfile
  gemfiles/sidekiq_4.2.gemfile
  gemfiles/sidekiq_5.0.gemfile
  gemfiles/sidekiq_5.1.gemfile
  gemfiles/sidekiq_5.2.gemfile
  gemfiles/sidekiq_6.0.gemfile
  gemfiles/sidekiq_develop.gemfile
  lib/sidekiq_unique_jobs.rb
  lib/sidekiq_unique_jobs/batch_delete.rb
  lib/sidekiq_unique_jobs/cli.rb
  lib/sidekiq_unique_jobs/config.rb
  lib/sidekiq_unique_jobs/exceptions.rb
  lib/sidekiq_unique_jobs/job.rb
  lib/sidekiq_unique_jobs/lock/base_lock.rb
  lib/sidekiq_unique_jobs/lock/validator.rb
  lib/sidekiq_unique_jobs/lock_args.rb
  lib/sidekiq_unique_jobs/lock_config.rb
  lib/sidekiq_unique_jobs/lock_digest.rb
  lib/sidekiq_unique_jobs/lock_timeout.rb
  lib/sidekiq_unique_jobs/lock_ttl.rb
  lib/sidekiq_unique_jobs/locksmith.rb
  lib/sidekiq_unique_jobs/on_conflict/replace.rb
  lib/sidekiq_unique_jobs/orphans/reaper.rb
  lib/sidekiq_unique_jobs/rspec/matchers.rb
  lib/sidekiq_unique_jobs/rspec/matchers/have_valid_sidekiq_options.rb
  lib/sidekiq_unique_jobs/sidekiq_unique_jobs.rb
  lib/sidekiq_unique_jobs/testing.rb
  lib/sidekiq_unique_jobs/upgrade_locks.rb
  lib/sidekiq_unique_jobs/web/helpers.rb
  spec/performance/lock_digest_spec.rb
  spec/sidekiq_unique_jobs/job_spec.rb
  spec/sidekiq_unique_jobs/lock_args_spec.rb
  spec/sidekiq_unique_jobs/lock_digest_spec.rb
  spec/sidekiq_unique_jobs/lock_timeout_spec.rb
  spec/sidekiq_unique_jobs/lock_ttl_spec.rb
  spec/sidekiq_unique_jobs/middleware/client_spec.rb
  spec/sidekiq_unique_jobs/options_with_fallback_spec.rb
  spec/spec_helper.rb
  spec/support/shared_contexts/with_sidekiq_options.rb
  spec/support/unique_macros.rb
  spec/workers/expiring_job_spec.rb
  spec/workers/my_unique_job_spec.rb
  spec/workers/until_expired_job_spec.rb
Labels: enhancement, master, v7.x

#435 remove deprecated/broken OptionsWithFallback#unique_type
  lib/sidekiq_unique_jobs/options_with_fallback.rb
  spec/sidekiq_unique_jobs/middleware/client_spec.rb
  spec/sidekiq_unique_jobs/options_with_fallback_spec.rb
Labels: master, v7.x

#476 Fix access to lock
  .rubocop.yml
  .simplecov
  .travis.yml
  Gemfile
  gemfiles/sidekiq_4.0.gemfile
  gemfiles/sidekiq_4.1.gemfile
  gemfiles/sidekiq_4.2.gemfile
  gemfiles/sidekiq_5.0.gemfile
  gemfiles/sidekiq_5.1.gemfile
  gemfiles/sidekiq_5.2.gemfile
  gemfiles/sidekiq_6.0.gemfile
  gemfiles/sidekiq_develop.gemfile
  lib/sidekiq_unique_jobs/cli.rb
  lib/sidekiq_unique_jobs/locksmith.rb
  lib/sidekiq_unique_jobs/version_check.rb
  lib/sidekiq_unique_jobs/web.rb
  spec/integration/sidekiq_unique_jobs/client/middleware_spec.rb
  spec/integration/sidekiq_unique_jobs/lock/while_executing_spec.rb
  spec/integration/sidekiq_unique_jobs/web_spec.rb
  spec/spec_helper.rb
  spec/unit/sidekiq_unique_jobs/cli_spec.rb
  spec/unit/sidekiq_unique_jobs/on_conflict/strategy_spec.rb
  spec/unit/sidekiq_unique_jobs/sidekiq_worker_methods_spec.rb
Labels: bug, v6.x

#477 Only configure RSpec when constant is defined
  lib/sidekiq_unique_jobs/rspec/matchers.rb
Labels: bug, master, v7.x

#479 Allow v7 configuration to work
  .rubocop.yml
  lib/sidekiq_unique_jobs/cli.rb
  lib/sidekiq_unique_jobs/constants.rb
  lib/sidekiq_unique_jobs/locksmith.rb
  redis/lock.lua
  spec/integration/sidekiq_unique_jobs/client/middleware_spec.rb
  spec/regression/issue_468_spec.rb
Labels: v6.x

#481 Fix bug where expiration wasn't set until unlock
  Gemfile
  gemfiles/sidekiq_4.0.gemfile
  gemfiles/sidekiq_4.1.gemfile
  gemfiles/sidekiq_4.2.gemfile
  gemfiles/sidekiq_5.0.gemfile
  gemfiles/sidekiq_5.1.gemfile
  gemfiles/sidekiq_5.2.gemfile
  gemfiles/sidekiq_6.0.gemfile
  gemfiles/sidekiq_develop.gemfile
  lib/sidekiq_unique_jobs/lua/lock.lua
  lib/sidekiq_unique_jobs/lua/queue.lua
  lib/sidekiq_unique_jobs/lua/unlock.lua
  lib/sidekiq_unique_jobs/unlockable.rb
  lib/sidekiq_unique_jobs/version.rb
  myapp/Gemfile
  sidekiq-unique-jobs.gemspec
  spec/sidekiq_unique_jobs/lock/until_executed_spec.rb
  spec/sidekiq_unique_jobs/lock/until_executing_spec.rb
  spec/sidekiq_unique_jobs/locksmith_spec.rb
  spec/sidekiq_unique_jobs/lua/lock_spec.rb
  spec/sidekiq_unique_jobs/lua/queue_spec.rb
  spec/sidekiq_unique_jobs/lua/unlock_spec.rb
  spec/sidekiq_unique_jobs/middleware/client_spec.rb
  spec/sidekiq_unique_jobs/middleware/server_spec.rb
  spec/sidekiq_unique_jobs/unlockable_spec.rb
  spec/sidekiq_unique_jobs/web_spec.rb
  spec/support/matchers/redis_matchers.rb
Labels: bug, master, v7.x

#482 Remove digest deletion for concurrent locks
  lib/sidekiq_unique_jobs/lua/unlock.lua
  spec/sidekiq_unique_jobs/lua/unlock_spec.rb
Labels: bug, master, v7.x

#483 Use thread-safe digest creation mechanism
  lib/sidekiq_unique_jobs/lock_digest.rb
Labels: bug, master, v6.x, v7.x

#484 Use thread-safe digest creation mechanism
  lib/sidekiq_unique_jobs/unique_args.rb
Labels: bug, v6.x
