Repository mhenrixon/sidekiq-unique-jobs, pull requests merged in 2021-12, with the labels that each got.

#666 Improve reaper performance under heavy load
  .reek.yml
  lib/sidekiq_unique_jobs/orphans/ruby_reaper.rb
  spec/sidekiq_unique_jobs/orphans/ruby_reaper_spec.rb
Labels: enhancement

#667 Fix homepage url
  sidekiq-unique-jobs.gemspec
Labels: bug

#674 Bump bundler and friends
  .github/workflows/lint.yml
  .github/workflows/rspec.yml
  Gemfile
  gemfiles/sidekiq_5.0.gemfile
  gemfiles/sidekiq_5.1.gemfile
  gemfiles/sidekiq_5.2.gemfile
  gemfiles/sidekiq_6.0.gemfile
  gemfiles/sidekiq_6.1.gemfile
  gemfiles/sidekiq_6.2.gemfile
  gemfiles/sidekiq_develop.gemfile
  spec/sidekiq_unique_jobs/middleware/client_spec.rb
  spec/sidekiq_unique_jobs/sidekiq_worker_methods_spec.rb
  spec/support/sidekiq_meta.rb
Labels: master, v7.x
