Repository mhenrixon/sidekiq-unique-jobs, pull requests merged in 2021-04, with the labels that each got.

#596 Fix uniqueness examples url in documentation
  README.md
Labels: documentation, v7.x

#595 Lock performance
  .github/workflows/lint.yml
  .github/workflows/rspec.yml
  .reek.yml
  Gemfile
  gemfiles/sidekiq_5.0.gemfile
  gemfiles/sidekiq_5.1.gemfile
  gemfiles/sidekiq_5.2.gemfile
  gemfiles/sidekiq_6.0.gemfile
  gemfiles/sidekiq_6.1.gemfile
  gemfiles/sidekiq_develop.gemfile
  lib/sidekiq_unique_jobs/lock/base_lock.rb
  lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb
  lib/sidekiq_unique_jobs/lock_config.rb
  lib/sidekiq_unique_jobs/locksmith.rb
  lib/sidekiq_unique_jobs/logging.rb
  spec/sidekiq_unique_jobs/lock/base_lock_spec.rb
  spec/sidekiq_unique_jobs/logging_spec.rb
Labels: enhancement, v7.x

#599 Fix recording lock_info
  .reek.yml
  lib/sidekiq_unique_jobs/lock_config.rb
  lib/sidekiq_unique_jobs/locksmith.rb
  lib/sidekiq_unique_jobs/sidekiq_unique_jobs.rb
  lib/sidekiq_unique_jobs/sidekiq_worker_methods.rb
  spec/sidekiq_unique_jobs/lock_config_spec.rb
  spec/sidekiq_unique_jobs/locksmith_spec.rb
Labels: bug, v7.x
