Repository mhenrixon/sidekiq-unique-jobs, pull requests merged in 2022-04, with the labels that each got.

#688 Fix drift
  .reek.yml
  lib/sidekiq_unique_jobs/locksmith.rb
  lib/sidekiq_unique_jobs/orphans/manager.rb
  lib/sidekiq_unique_jobs/testing.rb
  lib/sidekiq_unique_jobs/timer_task.rb
  spec/sidekiq_unique_jobs/changelog_spec.rb
  spec/sidekiq_unique_jobs/lock/until_and_while_executing_spec.rb
  spec/sidekiq_unique_jobs/lock/while_executing_reject_spec.rb
  spec/sidekiq_unique_jobs/lock/while_executing_spec.rb
  spec/sidekiq_unique_jobs/lock_args_spec.rb
  spec/sidekiq_unique_jobs/lock_config_spec.rb
  spec/sidekiq_unique_jobs/lock_digest_spec.rb
  spec/sidekiq_unique_jobs/lock_info_spec.rb
  spec/sidekiq_unique_jobs/locksmith_spec.rb
  spec/sidekiq_unique_jobs/lua/delete_job_by_digest_spec.rb
  spec/sidekiq_unique_jobs/lua/lock_spec.rb
  spec/sidekiq_unique_jobs/lua/queue_spec.rb
  spec/sidekiq_unique_jobs/lua/update_version_spec.rb
  spec/sidekiq_unique_jobs/middleware/client_spec.rb
  spec/sidekiq_unique_jobs/middleware/server/until_and_while_executing_spec.rb
  spec/sidekiq_unique_jobs/on_conflict/log_spec.rb
  spec/sidekiq_unique_jobs/on_conflict/raise_spec.rb
  spec/sidekiq_unique_jobs/on_conflict/reject_spec.rb
  spec/sidekiq_unique_jobs/on_conflict/replace_spec.rb
  spec/sidekiq_unique_jobs/on_conflict/reschedule_spec.rb
  spec/sidekiq_unique_jobs/on_conflict/strategy_spec.rb
  spec/sidekiq_unique_jobs/options_with_fallback_spec.rb
  spec/sidekiq_unique_jobs/orphans/manager_spec.rb
  spec/sidekiq_unique_jobs/orphans/reaper_resurrector_spec.rb
  spec/sidekiq_unique_jobs/redis/entity_spec.rb
  spec/sidekiq_unique_jobs/sidekiq_unique_jobs_spec.rb
  spec/sidekiq_unique_jobs/sidekiq_worker_methods_spec.rb
  spec/sidekiq_unique_jobs/update_version_spec.rb
  spec/sidekiq_unique_jobs/upgrade_locks_spec.rb
  spec/sidekiq_unique_jobs/version_check_spec.rb
  spec/sidekiq_unique_jobs/web_spec.rb
  spec/support/shared_examples/a_lockable_lock.rb
  spec/support/workers/really_simple_worker.rb
  spec/workers/unique_job_with_nil_unique_args_spec.rb
  spec/workers/while_executing_job_spec.rb
Labels: bug, master, v7.x

#698 Expire older changelog entries first
  .codeclimate.yml
  .reek.yml
  lib/sidekiq_unique_jobs/lock_digest.rb
  lib/sidekiq_unique_jobs/lua/shared/_common.lua
  lib/sidekiq_unique_jobs/testing.rb
  spec/sidekiq_unique_jobs/lock_args_spec.rb
Labels: bug

#699 Hotfix: Ensure consistent lock args
  lib/sidekiq_unique_jobs/lock_args.rb
Labels: bug, master, v7.x

#689 Quote '3.0' to ensure CI uses Ruby 3.0.x for the 3.0 entry
  .github/workflows/rspec.yml
Labels: enhancement, v7.x

#690 Abort Ruby Reaper when sidekiq queues are full
  .reek.yml
  lib/sidekiq_unique_jobs/orphans/ruby_reaper.rb
  spec/sidekiq_unique_jobs/orphans/ruby_reaper_spec.rb
Labels: enhancement, v7.x

#700 Make sure we reflect on execution failure
  lib/sidekiq_unique_jobs/lock/until_executed.rb
  lib/sidekiq_unique_jobs/lock/until_expired.rb
  lib/sidekiq_unique_jobs/lock/while_executing.rb
  spec/sidekiq_unique_jobs/lock/while_executing_spec.rb
  spec/support/shared_examples/a_lockable_lock.rb
Labels: enhancement

#702 Reimplement the entire TimerTask as it was
  .reek.yml
  lib/sidekiq_unique_jobs/timer_task.rb
Labels: bug, v7.x

#706 Manually handle timeouts
  .reek.yml
  bin/bundle
  lib/sidekiq_unique_jobs/orphans/manager.rb
  lib/sidekiq_unique_jobs/orphans/ruby_reaper.rb
  lib/sidekiq_unique_jobs/timer_task.rb
  lib/tasks/changelog.rake
  myapp/bin/bundle
  myapp/config/initializers/sidekiq.rb
  spec/sidekiq_unique_jobs/on_conflict/reject_spec.rb
  spec/sidekiq_unique_jobs/orphans/manager_spec.rb
  spec/sidekiq_unique_jobs/orphans/reaper_spec.rb
  spec/sidekiq_unique_jobs/orphans/ruby_reaper_spec.rb
  spec/spec_helper.rb
Labels: enhancement, v7.x

#707 Prepare for Sidekiq v7
  .reek.yml
  lib/sidekiq_unique_jobs/exceptions.rb
  lib/sidekiq_unique_jobs/lock_args.rb
  lib/sidekiq_unique_jobs/lock_config.rb
  lib/sidekiq_unique_jobs/lock_digest.rb
  lib/sidekiq_unique_jobs/lock_timeout.rb
  lib/sidekiq_unique_jobs/lock_ttl.rb
  lib/sidekiq_unique_jobs/middleware.rb
  lib/sidekiq_unique_jobs/on_conflict/reschedule.rb
  lib/sidekiq_unique_jobs/options_with_fallback.rb
  lib/sidekiq_unique_jobs/sidekiq_worker_methods.rb
  spec/performance/lock_digest_spec.rb
  spec/sidekiq/retry_set_spec.rb
  spec/sidekiq_unique_jobs/configuration_spec.rb
  spec/sidekiq_unique_jobs/job_spec.rb
  spec/sidekiq_unique_jobs/lock/until_and_while_executing_spec.rb
  spec/sidekiq_unique_jobs/lock/until_executed_spec.rb
  spec/sidekiq_unique_jobs/lock/until_executing_spec.rb
  spec/sidekiq_unique_jobs/lock/until_expired_spec.rb
  spec/sidekiq_unique_jobs/lock/while_executing_reject_spec.rb
  spec/sidekiq_unique_jobs/lock/while_executing_spec.rb
  spec/sidekiq_unique_jobs/lock_args_spec.rb
  spec/sidekiq_unique_jobs/lock_config_spec.rb
  spec/sidekiq_unique_jobs/lock_digest_spec.rb
  spec/sidekiq_unique_jobs/lock_timeout_spec.rb
  spec/sidekiq_unique_jobs/lock_ttl_spec.rb
  spec/sidekiq_unique_jobs/middleware/client/call_spec.rb
  spec/sidekiq_unique_jobs/middleware/server/call_spec.rb
  spec/sidekiq_unique_jobs/middleware/server/until_and_while_executing_spec.rb
  spec/sidekiq_unique_jobs/on_conflict/reschedule_spec.rb
  spec/sidekiq_unique_jobs/options_with_fallback_spec.rb
  spec/sidekiq_unique_jobs/sidekiq_worker_methods_spec.rb
  spec/sidekiq_unique_jobs/unlockable_spec.rb
  spec/spec_helper.rb
  spec/support/shared_contexts/with_sidekiq_options.rb
  spec/support/workers/simple_worker.rb
Labels: bug, enhancement, v7.x
